language: generic
branches:
  only:
   - staging
   - trying
   - master

env:
  - TARGET=ansiblecheck
  - TARGET=internal-minimal
  - TARGET=shellcheck
  - TARGET=shfmtcheck

install:
 - sudo ./scripts/docker-install-ubuntu.sh
 - ./scripts/docker-build.sh

script:
 - ./scripts/docker-run.sh make $TARGET
