#
# Copyright 2018 Delphix
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
#
# When using the APPLIANCE_PASSWORD variable, we have to be careful to
# specify "no_log" to prevent it from being leaked to stdout (e.g. if
# ansible is run with verbosity).
#
- fail:
    msg: "Required environment variable 'APPLIANCE_PASSWORD' is empty."
  when: lookup('env', 'APPLIANCE_PASSWORD') == ''
  no_log: true

- fail:
    msg: "Required environment variable 'APPLIANCE_USERNAME' is empty."
  when: lookup('env', 'APPLIANCE_USERNAME') == ''

- apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ant
    - git
  register: result
  until: result is not failed
  retries: 3
  delay: 60

#
# We need to do a shallow clone here for a couple reasons:
#
# 1. To reduce the size needed to transfer over the network, which
#    speeds up the time required to do a build.
#
# 2. To reduce the size of the resultant virtual machine images, which
#    speeds up the time to transfer these images to wherever they're
#    needed; along with reducing the cost of storing these images.
#
- git:
    repo: "{{ item.repo }}"
    dest:
      "/export/home/{{ lookup('env', 'APPLIANCE_USERNAME') }}/{{ item.dest }}"
    version: "{{ item.version }}"
    accept_hostkey: yes
    update: no
    depth: 1
  with_items:
    - { repo: 'https://gitlab.delphix.com/app/dlpx-app-gate.git',
        version: projects/dx4linux,
        dest: dlpx-app-gate }

- file:
    path: "/export/home/{{ lookup('env', 'APPLIANCE_USERNAME') }}/{{ item }}"
    owner: "{{ lookup('env', 'APPLIANCE_USERNAME') }}"
    group: staff
    state: directory
    recurse: yes
  with_items:
    - dlpx-app-gate

- authorized_key:
    user: "{{ lookup('env', 'APPLIANCE_USERNAME') }}"
    state: present
    key:
      "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAyvw2gQRkDqrRY5qxUn0VYAL6Rtt1/\
       NJhftc/KGt/66yinscWISJLzaumXW+GZ9KPgPb15hl0tWAdQxqeF6lmHVo5Ugj6e/\
       mJzDxN+1E39Ejj+lZbm1LCSjjp3Ly+fTkkmrUT1q9mSMbq8Pc1huCmX8MsFLwF7zh\
       56OlxQuTDjRqh8GMoy32JyKgddPjrL/YOhnfhxYirFHR+uXukRrtZbwI598d1gREe\
       kKkPncA5N/O6e/jD+JXxDYi2BPIIDZLb1yzFlHb8xMjXEkMPdfngv1Cs0ib//0qwG\
       etvKgydCTO7Au7b5Na3ArVlaokV96hVn8GpMt8SFpEbc6Fw3ul5uw=="

- lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - { key: "PermitRootLogin", value: "yes" }

- user:
    name: root
    password:
      "{{ lookup('env', 'APPLIANCE_PASSWORD') | password_hash('sha512') }}"
  no_log: true
